import type { Metadata } from 'next';
import * as stylex from '@stylexjs/stylex';
import './globals.css';
import Nav from '@/components/Nav';
import { tokens } from './tokens.stylex';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const styles = stylex.create({
  body: {
    height: '100dvh',
    color: tokens.primaryText,
  },
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body {...stylex.props(styles.body)}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
